server:
  port: 6969
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/user_management
    username: root
    password: Halodoc@123
    driver-class-name: com.mysql.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

